---
all:
  # vars:
  #   k8s_net: 10.10.4

  children:
    adm:
      hosts:
        192.168.0.33:
    k8s:
      children:
        masters:
          hosts:
            m1:
              ansible_host: "{{ k8s_net }}.101"
            m2:
              ansible_host: "{{ k8s_net }}.102"
            m3:
              ansible_host: "{{ k8s_net }}.103"

        workers:
          hosts:
            w1:
              ansible_host: "{{ k8s_net }}.111"
            w2:
              ansible_host: "{{ k8s_net }}.112"
            w3:
              ansible_host: "{{ k8s_net }}.113"
