---
- include_tasks: "setup-{{ ansible_os_family }}.yml"
- include_tasks: "CRI-Runtime-{{ ansible_os_family }}.yml"


- name: Install k8s all nodes packages
  package:
    name:
    - kubelet={{ k8s_version }}
    state: present
    
- name: Install k8s master packages
  package:
    name:
    - kubeadm={{ k8s_version }}
    state: present
  when: inventory_hostname in groups.masters

- name: Pushing /etc/crictl.yaml
  template: 
    src: crictl.yaml
    dest: /etc/crictl.yaml
    mode: u=rw,g=r,o=r