---
-  name: Install command line admin utils 
   package:
      name:
      - kubectl={{ k8s_version }}
      state: present

-  name: Get k8s facts
   include_tasks: tasks/get_k8s_facts.yml

-  name: Copy admin_config_file on ansible host
   fetch: 
      src: "{{ k8s_admin_config_file }}"
      dest: "/home/{{ lookup('env','USER') }}/.kube/config"
      flat: yes 
   when: k8s_initialized
   delegate_to: "{{ k8s_first_master }}"
   register: config_copy_present

-  name: Check "/home/{{ lookup('env','USER') }}/.kube" dir
   file:
      path: "/home/{{ lookup('env','USER') }}/.kube"
      state: directory

-  name: Copy admin_config_file to admin hosts
   copy: 
      src: "/home/{{ lookup('env','USER') }}/.kube/config"
      dest: "/home/{{ lookup('env','USER') }}/.kube/config"
   when: not config_copy_present.failed 
   register: config_copy_present_2


